import { BangkokStore, Product, ShoppingTrip, ExchangeConfig, Order, CustomRequest, User } from '@/types';

export const INITIAL_EXCHANGE_CONFIG: ExchangeConfig = {
  thbToIdrRate: 455, // 1 THB = Rp 455
  markupPercent: 12, // 12% standard service markup
  baseFeePerItemIDR: 20000, // Rp 20.000 jastip fee / item
  weightRatePer100gIDR: 12000, // Rp 12.000 per 100g (BKK -> JKT Air Cargo + Tax)
};

export const DEMO_USERS: (User & { password: string })[] = [
  {
    id: 'usr-customer-1',
    username: 'pembeli',
    password: 'password123',
    name: 'Alya Putri Maharani',
    role: 'CUSTOMER',
    phone: '081234567890',
    address: 'Jl. Senopati Raya No. 42, Kebayoran Baru',
    city: 'Jakarta Selatan',
  },
  {
    id: 'usr-customer-2',
    username: 'rina',
    password: 'password123',
    name: 'Rina Sasmita',
    role: 'CUSTOMER',
    phone: '081298765432',
    address: 'Jl. Boulevard Kelapa Gading Blok M No. 12',
    city: 'Jakarta Utara',
  },
  {
    id: 'usr-admin-1',
    username: 'admin',
    password: 'jastiper2026',
    name: 'Admin Jastipyudin (Bangkok Hub)',
    role: 'ADMIN',
    phone: '081122334455',
    address: 'Bangkok Hub Hotel Suite 402, Siam Square',
    city: 'Bangkok / Jakarta',
  },
];

export const BANGKOK_STORES: BangkokStore[] = [
  {
    id: 'eveandboy-siam',
    name: 'Eveandboy (Siam Square One)',
    thaiName: 'อีฟแอนด์บอย สยามสแควร์วัน',
    area: 'Siam & Ratchaprasong',
    description: 'Surga kosmetik & skincare terbesar di Bangkok dengan brand lokal Thailand & internasional terlengkap.',
    category: 'Beauty & Skincare',
    badgeColor: 'bg-pink-500',
    image: 'https://images.unsplash.com/photo-1596462502278-27bfdc403348?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'gentle-woman-siam',
    name: 'Gentle Woman Flagship Store',
    thaiName: 'เจนเทิล วูแมน สยามสแควร์',
    area: 'Siam & Ratchaprasong',
    description: 'Brand fashion viral nomor 1 Thailand. Canvas tote bags, clothing, dan aksesori estetik terkini.',
    category: 'Fashion & Bags',
    badgeColor: 'bg-amber-600',
    image: 'https://images.unsplash.com/photo-1544816155-12df9643f363?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'gmmtv-shop',
    name: 'GMMTV Shop (CentralWorld)',
    thaiName: 'จีเอ็มเอ็มทีวี ช็อป เซ็นทรัลเวิลด์',
    area: 'Siam & Ratchaprasong',
    description: 'Official merchandise store untuk aktor/artis serial GMMTV Thailand (Photocard, Lightstick, Dolls, Apparel).',
    category: 'Thai Pop & Merch',
    badgeColor: 'bg-blue-600',
    image: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'pratunam-market',
    name: 'Pratunam Fashion Market',
    thaiName: 'ตลาดประตูน้ำ กรุงเทพฯ',
    area: 'Pratunam',
    description: 'Pusat grosir pakaian Bangkok terbesar. Baju rajut, linen, dress tropical, dan fashion vintage kekinian.',
    category: 'Fashion & Bags',
    badgeColor: 'bg-emerald-600',
    image: 'https://images.unsplash.com/photo-1489987707025-afc232f7ea0f?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'chatuchak-market',
    name: 'Chatuchak Weekend Market',
    thaiName: 'ตลาดนัดจตุจักร',
    area: 'Chatuchak',
    description: 'Pasar akhir pekan legendaris dengan ribuan toko kerajinan lokal, spa aroma terapi, dan fashion unik.',
    category: 'Lifestyle & Handicraft',
    badgeColor: 'bg-purple-600',
    image: 'https://images.unsplash.com/photo-1513151233558-d860c5398176?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'big-c-rajdamri',
    name: 'Big C Supercenter (Rajdamri)',
    thaiName: 'บิ๊กซี ราชดำริ',
    area: 'Siam & Ratchaprasong',
    description: 'Pusat borong oleh-oleh camilan khas Thailand (Cha Tra Mue, Lay’s rasa lokal, dried fruits, permen susu).',
    category: 'Snacks & Food',
    badgeColor: 'bg-red-600',
    image: 'https://images.unsplash.com/photo-1578916171728-46686eac8d58?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'seven-eleven-thai',
    name: '7-Eleven Thailand',
    thaiName: 'เซเว่น อีเลฟเว่น ไทยแลนด์',
    area: 'All Bangkok Outlets',
    description: 'Convenience store legendaris dengan makanan siap saji hot toastie, snack eksklusif, dan sachet skincare viral.',
    category: '7-Eleven Specials',
    badgeColor: 'bg-green-600',
    image: 'https://images.unsplash.com/photo-1604719312566-8912e9227c6a?auto=format&fit=crop&w=800&q=80',
  },
];

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 'prod-gw-tote',
    name: 'Gentle Woman Canvas Tote Bag (Original)',
    thaiName: 'กระเป๋าผ้า เจนเทิล วูแมน',
    brand: 'Gentle Woman',
    category: 'FASHION',
    storeId: 'gentle-woman-siam',
    storeName: 'Gentle Woman Flagship Siam',
    priceTHB: 490,
    weightGrams: 280,
    image: 'https://images.unsplash.com/photo-1544816155-12df9643f363?auto=format&fit=crop&w=800&q=80',
    description: 'Tas kanvas viral dengan print logo bold ikonik Gentle Woman Bangkok. Material kanvas tebal 16oz dengan jahitan kokoh.',
    variants: ['Off-White Logo Hitam', 'All Black Logo Putih', 'Mini Dumpling Canvas'],
    popularBadge: '🔥 Best Seller Bangkok',
    isPreOrder: false,
    stockStatus: 'AVAILABLE',
  },
  {
    id: 'prod-4u2-jelly',
    name: '4U2 Jelly Tint Lip Stain (Viral Velvet Formula)',
    thaiName: 'โฟร์ยูทู เจลลี่ ทิ้นท์',
    brand: '4U2 Cosmetics',
    category: 'BEAUTY',
    storeId: 'eveandboy-siam',
    storeName: 'Eveandboy Siam Square One',
    priceTHB: 179,
    weightGrams: 40,
    image: 'https://images.unsplash.com/photo-1586495777744-4413f21062fa?auto=format&fit=crop&w=800&q=80',
    description: 'Liptint tekstur jelly lembut yang tidak transfer dan super tahan lama hingga 12 jam. Tidak membuat bibir kering.',
    variants: ['01 Gummy Bear', '03 Little Joy', '05 Baby Smile', '08 Love Like This'],
    popularBadge: '💄 Viral TikTok Thailand',
    isPreOrder: false,
    stockStatus: 'AVAILABLE',
  },
  {
    id: 'prod-mistine-mascara',
    name: 'Mistine Super Model Miracle Lash Mascara 4D',
    thaiName: 'มิสทิน ซุปเปอร์ โมเดล มาสคาร่า',
    brand: 'Mistine Thailand',
    category: 'BEAUTY',
    storeId: 'eveandboy-siam',
    storeName: 'Eveandboy Siam Square One',
    priceTHB: 159,
    weightGrams: 50,
    image: 'https://images.unsplash.com/photo-1512496015851-a90fb38ba796?auto=format&fit=crop&w=800&q=80',
    description: 'Mascara 2-in-1 dengan serat fiber pemanjang bulu mata hingga 400%. Waterproof dan tahan keringat tropis.',
    variants: ['Standard Jet Black'],
    popularBadge: '⭐ Must Have Skincare/Makeup',
    stockStatus: 'AVAILABLE',
  },
  {
    id: 'prod-chatramue-tea',
    name: 'Cha Tra Mue Original Thai Tea Leaf Red Bag 400g',
    thaiName: 'ชาตรามือ ชาไทยแท้ ถุงสีแดง',
    brand: 'Cha Tra Mue (Number One Brand)',
    category: 'SNACKS',
    storeId: 'big-c-rajdamri',
    storeName: 'Big C Supercenter Rajdamri',
    priceTHB: 135,
    weightGrams: 450,
    image: 'https://images.unsplash.com/photo-1576092768241-dec231879fc3?auto=format&fit=crop&w=800&q=80',
    description: 'Daun teh asli Thailand dengan aroma wangi vanila herbal khas Bangkok sejak 1945. Rahasia Thai Tea otentik wangi.',
    variants: ['Red Bag (Thai Tea Original)', 'Green Bag (Thai Green Tea 200g)', 'Gold Bag (Special Extra Aroma)'],
    popularBadge: '🧋 No. 1 Thai Tea',
    stockStatus: 'AVAILABLE',
  },
  {
    id: 'prod-lays-truffle',
    name: 'Lay\'s Thailand Exclusive Truffle & Salted Egg Flavors',
    thaiName: 'เลย์ รสทรัฟเฟิล และ ไข่เค็ม',
    brand: 'Lay\'s Thailand',
    category: 'SNACKS',
    storeId: 'big-c-rajdamri',
    storeName: 'Big C Supercenter Rajdamri',
    priceTHB: 48,
    weightGrams: 100,
    image: 'https://images.unsplash.com/photo-1566478989037-eec170784d0b?auto=format&fit=crop&w=800&q=80',
    description: 'Keripik kentang Lay\'s edisi khusus Thailand dengan aroma minyak Truffle mewah dan gurihnya Salted Egg.',
    variants: ['Truffle Flavor (75g)', 'Salted Egg Spicy (75g)', 'Thai Boat Noodle (75g)'],
    popularBadge: '🥔 Snack Terfavorit',
    stockStatus: 'AVAILABLE',
  },
  {
    id: 'prod-gmmtv-photocard',
    name: 'GMMTV Official Acrylic Standee & Exclusive Photocard Pack',
    thaiName: 'สแตนดี้และโฟโต้การ์ด จีเอ็มเอ็มทีวี',
    brand: 'GMMTV Official Store',
    category: 'THAI_POP',
    storeId: 'gmmtv-shop',
    storeName: 'GMMTV Shop CentralWorld',
    priceTHB: 450,
    weightGrams: 120,
    image: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&w=800&q=80',
    description: 'Merchandise resmi GMMTV Bangkok edisi terbaru. Termasuk hologram photocard + acrylic standee original Bangkok.',
    variants: ['Gemini-Fourth Set', 'Off-Gun Set', 'Tay-New Set', 'Win Metawin Official'],
    popularBadge: '✨ Exclusive Pop Merch',
    stockStatus: 'AVAILABLE',
  },
  {
    id: 'prod-poysian-inhaler',
    name: 'Poy-Sian Mark II Herbal Inhaler & Oil (Pack of 6)',
    thaiName: 'ยาดมตราโป๊ยเซียน มาร์ค ทู',
    brand: 'Poy-Sian Thailand',
    category: 'SEVEN_ELEVEN',
    storeId: 'seven-eleven-thai',
    storeName: '7-Eleven Thailand',
    priceTHB: 140,
    weightGrams: 150,
    image: 'https://images.unsplash.com/photo-1608248597358-1e428e833446?auto=format&fit=crop&w=800&q=80',
    description: 'Inhaler herbal nomor satu di Thailand dengan minyak peppermint, kayu putih, dan borneol untuk melegakan hidung dan pusing.',
    variants: ['1 Strip (Isi 6 Pcs)'],
    popularBadge: '🌿 Oleh-oleh Wajib',
    stockStatus: 'AVAILABLE',
  },
  {
    id: 'prod-pratunam-linen',
    name: 'Bangkok Premium Linen Oversized Resort Shirt',
    thaiName: 'เสื้อเชิ้ตผ้าลินิน ประตูน้ำ',
    brand: 'Pratunam Design Studio',
    category: 'FASHION',
    storeId: 'pratunam-market',
    storeName: 'Pratunam Fashion Market',
    priceTHB: 250,
    weightGrams: 220,
    image: 'https://images.unsplash.com/photo-1598033129183-c4f50c736f10?auto=format&fit=crop&w=800&q=80',
    description: 'Kemeja linen adem potongan oversized khas butik Pratunam Bangkok. Sangat cocok untuk iklim tropis santai.',
    variants: ['Sage Green (All Size)', 'Cream Sand (All Size)', 'Sky Blue (All Size)', 'Terracotta (All Size)'],
    popularBadge: '✨ Bangkok Summer Style',
    stockStatus: 'AVAILABLE',
  },
  {
    id: 'prod-smooto-tomato',
    name: 'Smooto Tomato Collagen White Serum (Box isi 6 Sachet)',
    thaiName: 'สมูทโตะ เซรั่มมะเขือเทศ',
    brand: 'Smooto Japan/Thailand',
    category: 'SEVEN_ELEVEN',
    storeId: 'seven-eleven-thai',
    storeName: '7-Eleven Thailand',
    priceTHB: 234,
    weightGrams: 180,
    image: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=800&q=80',
    description: 'Serum sachet tomat viral di 7-Eleven Bangkok yang setara dengan 10 buah tomat. Mencerahkan dan melembabkan kulit seketika.',
    variants: ['1 Box (Isi 6 Sachet)'],
    popularBadge: '🍅 7-Eleven Top Viral',
    stockStatus: 'AVAILABLE',
  },
];

export const INITIAL_TRIP: ShoppingTrip = {
  id: 'trip-bkk-jul-2026',
  title: 'Bangkok Shopping Spree: Siam, Pratunam & Chatuchak',
  destination: 'Bangkok, Thailand (BKK ✈️ CGK)',
  startDate: '3 Oct 2026',
  endDate: '7 Oct 2026',
  orderCloseDate: '3 Oct 2026, 23:59 WIB',
  flightDate: '7 Oct 2026',
  deliveryDate: '7 Oct 2026',
  status: 'LIVE_SHOPPING',
  quotaPercent: 82,
  currentShopperLocation: 'Siam Square One & CentralWorld',
  announcement: '📢 Shopper sedang belanja di Siam & Pratunam! Orderan ditutup besok malam pukul 23:59 WIB agar sempat dipacking rapi.',
};

export const INITIAL_CUSTOM_REQUESTS: CustomRequest[] = [
  {
    id: 'cr-101',
    userId: 'usr-customer-2',
    userName: 'Rina Sasmita',
    userPhone: '081298765432',
    itemName: 'Gentle Woman Club Tennis Skirt White (Size M)',
    brandOrStore: 'Gentle Woman Flagship Siam',
    notes: 'Mohon dicek jahitan pinggangnya ya kak, ambil Size M warna putih bersih.',
    referenceUrl: 'https://gentlewomanonline.com',
    imageUrl: 'https://images.unsplash.com/photo-1544816155-12df9643f363?auto=format&fit=crop&w=800&q=80',
    targetPriceTHB: 1290,
    estimatedWeightGrams: 350,
    status: 'APPROVED',
    adminNotes: 'Stok ada di Siam Square One lantai 2, siap dibelikan siang ini.',
    quotedPriceTHB: 1290,
    createdAt: '2026-07-13T10:15:00Z',
  },
  {
    id: 'cr-102',
    userId: 'usr-customer-1',
    userName: 'Alya Putri Maharani',
    userPhone: '081234567890',
    itemName: 'Carmine Red Cha Tra Mue Tumbler Stainless 500ml',
    brandOrStore: 'Cha Tra Mue IconSiam',
    notes: 'Warna Merah Carmine edisi Natal/Anniversary kalau masih ada.',
    imageUrl: 'https://images.unsplash.com/photo-1576092768241-dec231879fc3?auto=format&fit=crop&w=800&q=80',
    targetPriceTHB: 350,
    estimatedWeightGrams: 400,
    status: 'PENDING_REVIEW',
    adminNotes: 'Sedang dicek ketersediaan stok di outlet Siam Paragon.',
    quotedPriceTHB: 350,
    createdAt: '2026-07-13T11:40:00Z',
  }
];

export const INITIAL_ORDERS: Order[] = [
  {
    id: 'ord-bkk-8891',
    userId: 'usr-customer-1',
    orderNumber: 'JSTP-TH-8891',
    customerName: 'Alya Putri Maharani',
    customerWhatsapp: '081234567890',
    customerAddress: 'Jl. Senopati Raya No. 42, Kebayoran Baru',
    customerCity: 'Jakarta Selatan',
    items: [
      {
        id: 'ci-1',
        userId: 'usr-customer-1',
        productId: 'prod-gw-tote',
        name: 'Gentle Woman Canvas Tote Bag (Original)',
        storeName: 'Gentle Woman Flagship Siam',
        priceTHB: 490,
        quantity: 1,
        weightGrams: 280,
        selectedVariant: 'Off-White Logo Hitam',
        image: 'https://images.unsplash.com/photo-1544816155-12df9643f363?auto=format&fit=crop&w=800&q=80',
      },
      {
        id: 'ci-2',
        userId: 'usr-customer-1',
        productId: 'prod-4u2-jelly',
        name: '4U2 Jelly Tint Lip Stain',
        storeName: 'Eveandboy Siam Square One',
        priceTHB: 179,
        quantity: 2,
        weightGrams: 80,
        selectedVariant: '01 Gummy Bear',
        image: 'https://images.unsplash.com/photo-1586495777744-4413f21062fa?auto=format&fit=crop&w=800&q=80',
      }
    ],
    subtotalTHB: 848,
    subtotalIDR: 385840,
    jastipFeeIDR: 60000,
    weightFeeIDR: 48000,
    totalIDR: 493840,
    paymentMethod: 'QRIS',
    paymentStatus: 'CONFIRMED',
    status: 'PACKED_READY',
    createdAt: '2026-07-13T09:30:00Z',
    trackingNumber: 'PXL-BKK24-88910X',
    trackingSteps: [
      {
        status: 'AWAITING_PAYMENT',
        title: 'Pesanan Dibuat & Menunggu Pembayaran',
        description: 'Pembayaran Total Jastip berhasil diverifikasi.',
        location: 'Jakarta, Indonesia',
        timestamp: '13 Jul 2026, 09:35 WIB',
        completed: true,
      },
      {
        status: 'SHOPPING',
        title: 'Barang Sedang Dibeli',
        description: 'Struk toko & foto fisik barang telah diverifikasi oleh Shopper.',
        location: 'Eveandboy Siam & Gentle Woman Store',
        timestamp: '13 Jul 2026, 14:15 WIB',
        completed: true,
      },
      {
        status: 'PACKED_READY',
        title: 'Barang Dipacking & Siap Dikirim',
        description: 'Barang dibungkus bubble wrap lapis 3 & kardus koper.',
        location: 'Bangkok, Thailand',
        timestamp: '14 Jul 2026, 10:00 WIB',
        completed: true,
        current: true,
        photoProofUrl: 'https://images.unsplash.com/photo-1544816155-12df9643f363?auto=format&fit=crop&w=800&q=80',
      },
      {
        status: 'ARRIVED_JKT',
        title: 'Barang Tiba di Jakarta',
        description: 'Barang sudah tiba di Jakarta dan siap diserahkan.',
        location: 'Jakarta, Indonesia',
        completed: false,
      },
      {
        status: 'DELIVERED',
        title: 'Dikirim ke Alamat Kamu',
        description: 'Konfirmasi barang sudah kamu terima dengan baik.',
        location: 'Jakarta Selatan',
        completed: false,
      }
    ]
  }
];
